// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models
{
    [Table("Department")]
    public partial class Department
    {
        public Department()
        {
            Students = new HashSet<Student>();
        }

        [Key]
        public int DeptId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("Dept")]
        public virtual ICollection<Student> Students { get; set; }
    }
}